exports.STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOCONTENT: 204,
  BADREQUEST: 400,
  UN_AUTHORIZED: 401,
  FORBIDDEN: 403,
  NOTFOUND: 404,
  TIMEOUT: 408,
  TOOMANYREQ: 429,
  INTERNALSERVER: 500,
  BADGATEWAYS: 502,
  SERVICEUNAVILABLE: 503,
  GATEWAYTIMEOUT: 504
};

exports.RES_MSG = {
  CREATEUSER: 'User created succesfully',
  LOGSUCCESS: 'User successfully logged in',
  USEREXIST: 'User already exist',
  INVALIDLOG: 'Email/password is invalid',
  NODOMAIN: 'No domain found',
  DOMAINFOUND: 'Domain details found',
  DOMAINBUY: 'Domain purchased successful',
  CONTROLBUY: 'Controller purchase successful',
  DOMAIN_OWNER: 'You are not the owner of this domain',
  SEARCH_SUB_DOMAIN: 'Searched all sub_domains',
  SEARCH_DOMAIN: 'Searched all domains',
  NOSUB_DOMAIN: 'No sub domain found',
  SUBDOMAIN_CON_DETAILS: 'Sub domain controller details',
  TRANSFERFAIL: 'Transfer failed',
  NOWALLET: 'No wallet found',
  DOMAINTRANSFER: 'Domain transfered successfully',
  INVALIDTOKENID: 'Invalid Token Id',
  ADDRESSFETCH: 'Address Fetched Successfully',
  BALANCEFETCH: 'Balance Fetched Successfully',
  BLOCKFETCH: 'Block Fetched Successfully',
  TRANSFERBALANCE: 'Balance Transfered Successfully',
  BLOCKDETAIL: 'Block Detail Fetched Successfully',
  ERROR: 'Oops! Something went wrong. Please try again.',
  ALLBLOCKFETCH: 'Block Fetched Successfully',
  VALIDHASH: 'Please Enter a Valid Hash',
  TRASACTION: 'Transaction Fetched Successfully',
  PEERSFETCH: 'Peers Fetched Successfully',
  VALIDATORFETCH: 'Validator Fetched Successfully',
  KEYFETCH: 'Key Fetch Successfully',
  PREIMAGESUCCESS: 'Pre Image Created Successfully',
  PROPOSALSUBMIT: 'Proposal Submit Successfully',
  VOTESENT: 'Vote Sent Successfully',
  DISPETCHFETCH: 'Dispetch Fetched Successfully',
  BALANCETRANSFERED: 'Balance Transfered Successfully',
  EXCEEDSBALANCE:
    'We could not transferred balance because you already have balance',
  TRANSACTIONFETCH: 'Transaction fetch Successfully',
  BLOCKTRANSACTIONFETCH: 'Block transactions fetched Successfully',
  APPROVEDFETCH: 'Approved Fetch Successfully',
  OWNEROFFETCH: 'Owner Of Fetch Successfully',
  INVALIDADDRESSS: 'Invalid Address',
  MINTSUCCESS: 'Mint Successfully',
  TOKENIDEXIST: 'Token Id already exist',
  INVALIDRECIEVERACCOUNTID: 'Invalid Reciever Account Id',
  FILEREQUIRED: 'Only 1 file is required',
  BURNSUCCESS: 'Burn Successfully',
  TRANSFERSUCCESS: 'Transfer Successfully',
  INVALIDTOADDRESS: 'Invalid toAddress',
  INVALIDACCOUNTID: 'Invalid Account Id',
  INVALIDOPERATORID: 'Invalid Operator Id',
  INVALIDOWNERID: 'Invalid Owner Id',
  INVALIDFROMACCOUNT: 'Invalid from Account Id',
  INVALIDTOACCOUNT: 'Invalid to Account Id',
  APPROVESUCCESS: 'Approve Successfully',
  APPROVALSET: 'Approval Set Successfully',
  NFTFETCH: 'NFT Fetch Successfully',
  INVALIDOWNERMNEMONICS: 'Invali Nft Owner Mnemonics',
  NOTTRANSFERTOKEN: 'You did not transfer the token to yourself',
  INVALIDFILESIZE: 'Invalid File Size',
  FILEXIST: 'File already exist,Please add unique file',
  INVALID_HASH: 'Hash is not valid',
  SERVER_ERROR: 'Server Error',
  NOT_FOUND: 'Not Found!',
  BLOCKADDED: 'Block Added Successfully!',
  UPDATED_SUCCESS: 'Updated Successfully!',
  NOT_VALID_BLOCK_NUMBER: 'Not Valid Block Number!',
  NOT_VALID_QUERY: 'Query is not Valid!',
  INVALIDADDREASS: 'Invalid Address!',
  HOST_NOT_CONNECTED: 'Node host not connected!',
  INVALIDMNEMONICS: 'Invalid Mnemonics',
  MANAGER: 'Invalid  Manager',
  ADMIN: 'Manager Will Be Updated By Admin Only',
  HIGHAMOUNT: 'Amount is grater than maxSupply'
};

exports.MIDDLEWARE_RESPONSE = {
  JWTERROR: 'Unauthorize Request',
  PERMISSION_DENIED: 'Permission denied for this user.',
  ONLY_LOGIN_WORKS: 'The feature is temporarily disabled.'
};
